Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -1,7 +1,4 @@
-# This workflow will install Python dependencies, run tests and lint with a single version of Python
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
-
-name: Python application
+name: CI/CD Python
 
 on:
   push:
@@ -13,10 +10,8 @@ permissions:
   contents: read
 
 jobs:
-  build:
-
+  test-code:
     runs-on: ubuntu-latest
-
     steps:
     - uses: actions/checkout@v4
     - name: Set up Python 3.10
@@ -31,4 +26,65 @@ jobs:
     - name: Test with pytest
       run: |
         export PYTHONPATH=${PWD}/src:${PYTHONPATH}
-        pytest
+        pytest && echo "Unit tests passed!" || echo "Unit tests failed!"
+    - name: Upload test results
+      uses: actions/upload-artifact@v4
+      with:
+        name: test-code-results
+        path: reports/test-code-results.xml
+          
+  build-wheel:
+    name: Build Wheel
+    runs-on: ubuntu-latest
+    needs: test-code
+    steps:
+    - uses: actions/checkout@v4
+    - name: Set up Python 3.10
+      uses: actions/setup-python@v3
+      with:
+        python-version: 3.10
+    - name: Install build tools
+      run: |
+        echo "Installing CI/CD Python wheels..."
+        export PYTHONPATH=${PWD}/src:${PYTHONPATH}
+        pip install --upgrade pip setuptools wheel
+        pip install build
+    - name: Build wheel
+      run: |
+        echo "Compiling/Building the Python wheel..."
+        chmod +x build_wheel.sh
+        ./build_wheel.sh
+    - name: Upload wheel
+      uses: actions/upload-artifact@v4
+      with:
+        name: dist
+        path: dist/*.whl
+
+    
+  test-wheel:
+    name: Test Built Wheel
+    runs-on: ubuntu-latest
+    needs: build-wheel
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.10
+      - name: Download wheel
+        uses: actions/download-artifact@v4
+        with:
+          name: dist
+          path: dist
+      - name: Install and test wheel
+        run: |
+          echo "Installing the built wheel..."
+          pip install dist/*.whl
+          echo "Testing the wheel"
+          scikit_learn_bench && echo "Test CLI passed!" || echo "Test CLI failed!"
+          python3 -c "import scikit_learn_bench" && echo "Test import passed!" || echo "Test import failed!"
+      - name: Upload test results
+        uses: actions/upload-artifact@v4
+        with:
+          name: test2-results
+          path: reports/test2-results.xml
